### ISSUE TITLE
google plus login

### ISSUE THREAD

**Issue by rahulmool** [nncl/capacitor-testing#1]
I am trying to sign in with google using ionic 4 but i can not login can you tell me how you were able to do so ?

**Comment by nncl** [comment]
Hello. @rahulmool Could you provide some more information on what either you're doing or if any errors are returned on your logs. Are you trying to emulate on devices or simulators? Or both?

Are you filling all required information such as REVERSED_CLIENT_ID?

I didn't commit on this repo some information/files such as **GoogleService-Info.plist** and **Info.plist** in order to hide some private data. So maybe you're not generating these information?

**Comment by rahulmool** [comment]
I didn't filled REVERSED_CLIENT_ID . But now the error is gone. Still thanks for replying 😊.
